package com.example.game.island.building

import com.example.game.resource.ResourceType

object BuildingConfigRepository {

    private val configs = mapOf(
        BuildingType.MAIN_HOUSE to BuildingConfig(
            buildingType = BuildingType.MAIN_HOUSE,
            description = "The central heart of your island. Controls overall village level and unlocks new land.",
            category = "SPECIAL",
            width = 3,
            height = 3,
            baseCostCoins = 500L,
            baseCostWood = 20,
            baseCostStone = 10,
            growthMultiplier = 1.8,
            baseConstructionDurationSecs = 30,
            productionType = ResourceType.COINS,
            baseProductionPerHour = 100L,
            requiredPlayerLevel = 1,
            requiredStars = 0
        ),
        BuildingType.HOUSE to BuildingConfig(
            buildingType = BuildingType.HOUSE,
            description = "Cozy island home. Generates steady coins over time.",
            category = "PRODUCTION",
            width = 2,
            height = 2,
            baseCostCoins = 100L,
            baseCostWood = 5,
            growthMultiplier = 1.6,
            baseConstructionDurationSecs = 15,
            productionType = ResourceType.COINS,
            baseProductionPerHour = 30L,
            requiredPlayerLevel = 1,
            requiredStars = 0
        ),
        BuildingType.WOOD_HUT to BuildingConfig(
            buildingType = BuildingType.WOOD_HUT,
            description = "Simple lumber jack hut that harvests fresh wood.",
            category = "PRODUCTION",
            width = 2,
            height = 2,
            baseCostCoins = 150L,
            baseCostWood = 0,
            growthMultiplier = 1.6,
            baseConstructionDurationSecs = 15,
            productionType = ResourceType.WOOD,
            baseProductionPerHour = 25L,
            requiredPlayerLevel = 1,
            requiredStars = 0
        ),
        BuildingType.STONE_WORKSHOP to BuildingConfig(
            buildingType = BuildingType.STONE_WORKSHOP,
            description = "Workshop that processes raw stone into sturdy bricks.",
            category = "PRODUCTION",
            width = 2,
            height = 2,
            baseCostCoins = 250L,
            baseCostWood = 10,
            growthMultiplier = 1.7,
            baseConstructionDurationSecs = 20,
            productionType = ResourceType.STONE,
            baseProductionPerHour = 20L,
            requiredPlayerLevel = 1,
            requiredStars = 0
        ),
        BuildingType.FOOD_FARM to BuildingConfig(
            buildingType = BuildingType.FOOD_FARM,
            description = "Produces delicious crops and food supplies.",
            category = "PRODUCTION",
            width = 2,
            height = 2,
            baseCostCoins = 200L,
            baseCostWood = 10,
            growthMultiplier = 1.6,
            baseConstructionDurationSecs = 20,
            productionType = ResourceType.FOOD,
            baseProductionPerHour = 30L,
            requiredPlayerLevel = 1,
            requiredStars = 0
        ),
        BuildingType.METAL_WORKSHOP to BuildingConfig(
            buildingType = BuildingType.METAL_WORKSHOP,
            description = "Forges high-durability iron and metal bars.",
            category = "PRODUCTION",
            width = 2,
            height = 2,
            baseCostCoins = 350L,
            baseCostWood = 15,
            baseCostStone = 15,
            growthMultiplier = 1.8,
            baseConstructionDurationSecs = 30,
            productionType = ResourceType.METAL,
            baseProductionPerHour = 15L,
            requiredPlayerLevel = 2,
            requiredStars = 5
        ),
        BuildingType.WORKSHOP to BuildingConfig(
            buildingType = BuildingType.WORKSHOP,
            description = "Crafts durable timber for construction and upgrades.",
            category = "PRODUCTION",
            width = 2,
            height = 2,
            baseCostCoins = 200L,
            baseCostWood = 0,
            baseCostStone = 5,
            growthMultiplier = 1.7,
            baseConstructionDurationSecs = 20,
            productionType = ResourceType.WOOD,
            baseProductionPerHour = 20L,
            requiredPlayerLevel = 1,
            requiredStars = 0
        ),
        BuildingType.MINE to BuildingConfig(
            buildingType = BuildingType.MINE,
            description = "Extracts sturdy stone from the island quarries.",
            category = "PRODUCTION",
            width = 2,
            height = 2,
            baseCostCoins = 300L,
            baseCostWood = 10,
            growthMultiplier = 1.8,
            baseConstructionDurationSecs = 30,
            productionType = ResourceType.STONE,
            baseProductionPerHour = 15L,
            requiredPlayerLevel = 2,
            requiredStars = 5
        ),
        BuildingType.FARM to BuildingConfig(
            buildingType = BuildingType.FARM,
            description = "Produces fresh food crops to supply your islanders.",
            category = "PRODUCTION",
            width = 2,
            height = 2,
            baseCostCoins = 250L,
            baseCostWood = 10,
            growthMultiplier = 1.7,
            baseConstructionDurationSecs = 25,
            productionType = ResourceType.FOOD,
            baseProductionPerHour = 25L,
            requiredPlayerLevel = 1,
            requiredStars = 0
        ),
        BuildingType.STORAGE to BuildingConfig(
            buildingType = BuildingType.STORAGE,
            description = "Expands your island storage capacity for all raw materials.",
            category = "STORAGE",
            width = 2,
            height = 2,
            baseCostCoins = 400L,
            baseCostWood = 15,
            baseCostStone = 15,
            growthMultiplier = 1.8,
            baseConstructionDurationSecs = 35,
            productionType = ResourceType.COINS,
            baseProductionPerHour = 0L,
            requiredPlayerLevel = 2,
            requiredStars = 5
        ),
        BuildingType.BAKERY to BuildingConfig(
            buildingType = BuildingType.BAKERY,
            description = "Bakes delicious treats that generate high gold income.",
            category = "PRODUCTION",
            width = 2,
            height = 2,
            baseCostCoins = 600L,
            baseCostWood = 20,
            baseCostStone = 10,
            growthMultiplier = 1.9,
            baseConstructionDurationSecs = 45,
            productionType = ResourceType.FOOD,
            baseProductionPerHour = 40L,
            requiredPlayerLevel = 3,
            requiredStars = 10
        ),
        BuildingType.MARKET to BuildingConfig(
            buildingType = BuildingType.MARKET,
            description = "A bustling trade hub where resources can be exchanged.",
            category = "UTILITY",
            width = 3,
            height = 2,
            baseCostCoins = 1000L,
            baseCostWood = 30,
            baseCostStone = 20,
            growthMultiplier = 2.0,
            baseConstructionDurationSecs = 60,
            productionType = ResourceType.COINS,
            baseProductionPerHour = 80L,
            requiredPlayerLevel = 4,
            requiredStars = 15
        ),
        BuildingType.DECORATION_SHOP to BuildingConfig(
            buildingType = BuildingType.DECORATION_SHOP,
            description = "Shop offering decorative items to boost island beauty.",
            category = "UTILITY",
            width = 2,
            height = 2,
            baseCostCoins = 500L,
            baseCostWood = 15,
            baseCostStone = 10,
            growthMultiplier = 1.7,
            baseConstructionDurationSecs = 30,
            productionType = ResourceType.COINS,
            baseProductionPerHour = 20L,
            requiredPlayerLevel = 2,
            requiredStars = 5
        ),
        BuildingType.ENERGY_HOUSE to BuildingConfig(
            buildingType = BuildingType.ENERGY_HOUSE,
            description = "Restores match-3 energy over time.",
            category = "UTILITY",
            width = 2,
            height = 2,
            baseCostCoins = 800L,
            baseCostWood = 25,
            baseCostStone = 25,
            growthMultiplier = 1.9,
            baseConstructionDurationSecs = 45,
            productionType = ResourceType.ENERGY,
            baseProductionPerHour = 1L,
            requiredPlayerLevel = 3,
            requiredStars = 10
        ),
        BuildingType.SPECIAL_BUILDING to BuildingConfig(
            buildingType = BuildingType.SPECIAL_BUILDING,
            description = "Grand monument showcasing your island's prosperity.",
            category = "SPECIAL",
            width = 3,
            height = 3,
            baseCostCoins = 3000L,
            baseCostWood = 100,
            baseCostStone = 100,
            baseCostMetal = 50,
            growthMultiplier = 2.2,
            baseConstructionDurationSecs = 120,
            productionType = ResourceType.GEMS,
            baseProductionPerHour = 1L,
            requiredPlayerLevel = 5,
            requiredStars = 30
        ),
        BuildingType.LUMBER_MILL to BuildingConfig(
            buildingType = BuildingType.LUMBER_MILL,
            description = "Advanced wood processing plant.",
            category = "PRODUCTION",
            width = 2,
            height = 2,
            baseCostCoins = 500L,
            baseCostWood = 20,
            baseCostStone = 10,
            growthMultiplier = 1.8,
            baseConstructionDurationSecs = 40,
            productionType = ResourceType.WOOD,
            baseProductionPerHour = 50L,
            requiredPlayerLevel = 3,
            requiredStars = 10
        ),
        BuildingType.HARBOR to BuildingConfig(
            buildingType = BuildingType.HARBOR,
            description = "Maritime dock connecting trade routes across worlds.",
            category = "UTILITY",
            width = 3,
            height = 2,
            baseCostCoins = 1200L,
            baseCostWood = 50,
            baseCostStone = 30,
            growthMultiplier = 2.0,
            baseConstructionDurationSecs = 90,
            productionType = ResourceType.COINS,
            baseProductionPerHour = 120L,
            requiredPlayerLevel = 4,
            requiredStars = 20
        ),
        BuildingType.LABORATORY to BuildingConfig(
            buildingType = BuildingType.LABORATORY,
            description = "Researches alchemy recipes and material transmutations.",
            category = "UTILITY",
            width = 2,
            height = 2,
            baseCostCoins = 1500L,
            baseCostWood = 40,
            baseCostStone = 40,
            growthMultiplier = 2.1,
            baseConstructionDurationSecs = 90,
            productionType = ResourceType.GEMS,
            baseProductionPerHour = 1L,
            requiredPlayerLevel = 5,
            requiredStars = 25
        ),
        BuildingType.MAGIC_TOWER to BuildingConfig(
            buildingType = BuildingType.MAGIC_TOWER,
            description = "Mystical tower radiating magic energy across the island.",
            category = "SPECIAL",
            width = 2,
            height = 2,
            baseCostCoins = 2000L,
            baseCostWood = 60,
            baseCostStone = 60,
            growthMultiplier = 2.2,
            baseConstructionDurationSecs = 100,
            productionType = ResourceType.GEMS,
            baseProductionPerHour = 1L,
            requiredPlayerLevel = 6,
            requiredStars = 35
        )
    )

    fun getConfig(type: BuildingType): BuildingConfig {
        return configs[type] ?: configs[BuildingType.HOUSE]!!
    }

    fun getAllConfigs(): List<BuildingConfig> {
        return configs.values.toList()
    }

    fun getConfigsByCategory(category: String): List<BuildingConfig> {
        if (category == "ALL") return getAllConfigs()
        return configs.values.filter { it.category.equals(category, ignoreCase = true) }
    }
}
